# Generated by Django 2.2.4 on 2019-08-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('s', 'satisfied'), ('w', 'waiting'), ('a', 'available')], default='a', max_length=5),
        ),
    ]
