# Generated by Django 2.2.4 on 2019-08-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='issuer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ticket',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='game',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reject_counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='row',
            field=models.CharField(default='any', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='section',
            field=models.CharField(default='any', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('buy', 'buying'), ('sell', 'selling')], max_length=5),
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
