# Generated by Django 2.2.4 on 2019-08-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20190829_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
